{{- if .Values.testPod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "bundleutils.name" . }}-github-ssh-test
  labels:
    app.kubernetes.io/name: {{ include "bundleutils.name" . }}
    helm.sh/chart: {{ include "bundleutils.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  containers:
    - name: bundleutils-testgitssh
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      envFrom:
        - secretRef:
            name: {{ .Values.bundleUtilsSecrets.name }}
      command:
        - /bin/sh
        - -c
        - |
          set -x      
          SSH_PATH='/root/.ssh'
          ls -la $SSH_PATH
          SSH_KEY=$SSH_PATH/privateKey
          SSH_CONFIG=$SSH_PATH/config
          SSH_KNOWN_HOSTS=$SSH_PATH/known_hosts
          echo "###### SSH_KEY"
          cat ${SSH_KEY}
          echo "###### SSH_CONFIG"
          cat ${SSH_CONFIG}
          echo "###### SSH_KNOWN_HOSTS"
          cat ${SSH_KNOWN_HOSTS}
          ssh -o UserKnownHostsFile=${SSH_KNOWN_HOSTS} -i $SSH_KEY git@github.com
          git config --global user.email {{ .Values.bundleUtilsSecrets.data.GIT_COMMITTER_EMAIL }}
          git config --global user.name {{ .Values.bundleUtilsSecrets.data.GIT_COMMITTER_NAME }}
          git clone {{ .Values.bundleUtilsSecrets.data.GIT_REPO }}
          cd $(basename -s .git "{{ .Values.bundleUtilsSecrets.data.GIT_REPO }}")
          echo "# Auto Update from Pod {{ include "bundleutils.name" . }}-git-ssh-test $(date)" >> README.md
          git add .
          git commit -m "Auto update from Pod {{ include "bundleutils.name" . }}-git-ssh-test"
          git push origin main
      volumeMounts:
        - name: ssh-key
          mountPath: /root/.ssh/
          readOnly: true
  restartPolicy: {{ .Values.testPod.restartPolicy }}
  volumes:
    - name: ssh-key
      secret:
        secretName: {{ .Values.sshSecret.name }}
        defaultMode: 0600
{{- end }}
