apiVersion: batch/v1
kind: CronJob
metadata:
  name: bundleutils-audit
spec:
  schedule: "*/2 * * * *" # every minute
  #schedule: "0 */1 * * *" # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              envFrom:
                - secretRef:
                    name: bundle-utils-secrets
              image: caternberg/bundleutils:dev3
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  date
                  env | sort
                  set -x
                  SSH_KEY_PATH=/root/.ssh/id_rsa        
                  # file ~/.ssh/id_rsa
                  cat ${SSH_KEY_PATH}
                  eval `ssh-agent -s`
                  ssh-add ${SSH_KEY_PATH}
                  #ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                  git config --global user.email ${GIT_COMMITTER_EMAIL}
                  git config --global user.name ${GIT_COMMITTER_NAME}
                  git clone ${GIT_REPO}
                  cd $(basename -s .git "${GIT_REPO}")    
                  /opt/bundleutils/work/examples/tutorials/auditing/audit.sh
              volumeMounts:
                - name: ssh-key
                  mountPath: /root/.ssh/
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: ssh-key
              secret:
                secretName: secret-ssh-auth
                defaultMode: 0600
